const daftarNamaGuru = [
    "Abdul Kiflih",
    "Adam Ramadhan",
    "Ahmad Diya'ul Hakkih, S.Pd.I.",
    "Alfan Ichwan Habibi, S.Pd.",
    "Anisatul Musrifah, S.Pd.",
    "Bi'iizetil Kamilah",
    "Devi Oktaviana",
    "Hakiki, S.Pd.",
    "Holipah",
    "I'anatul Muhtaromah, S.Pd.",
    "Inayatun Holidiah, S.Pd.",
    "Insanul Kamil",
    "Kurnia Nurandini Susilowati",
    "Lala Anggi Dwi Agusti, S.Pd.",
    "Latifah, S.Pd.",
    "Luluk Lestari Nur'ainy, S.Pd.",
    "M. Hodri Ali Wafi, S.E",
    "Nadiah",
    "Nur Holida, S.Pd.",
    "Rahmat Hidayat",
    "Rahmattullah",
    "Rodi, S.Pd.",
    "Siti Mutmainnah, S.Pd.",
    "Sitti Afrak, S.Pd.",
    "Sitti Khotijah",
    "Sitti Salimah",
    "Zaenap, S.H."
];

const daftarMapel = [
    "Bahasa Indonesia",
    "Bahasa Inggris",
    "Bahasa Madura",
    "Baca Tulis Al-Qur'an (BTQ)",
    "Dasar Penanganan Bahan Hasil Pertanian (DPBHP)",
    "Dasar Pengolahan Produk Hasil Pertanian (DPPHP)",
    "Dasar Proses Pengolahan Hasil Pertanian (DPPHP)",
    "Ilmu Pengetahuan Alam (IPA)",
    "Ilmu Pengetahuan Alam dan Sosial (IPAS)",
    "Ilmu Pengetahuan Sosial (IPS)",
    "Keamanan Pangan, Penyimpanan, dan Penggudangan (K3P)",
    "Literasi dan Numerasi",
    "Matematika (MTK)",
    "Pengolahan Produk Hasil Hewani (PPHH)",
    "Pengolahan Produk Hasil Nabati (PPHN)",
    "Pendidikan Agama Islam (PAI)",
    "Pendidikan Jasmani, Olahraga, dan Kesehatan (PJOK)",
    "Pendidikan Pancasila dan Kewarganegaraan (PPKn)",
    "Prakarya",
    "Produk Kreatif dan Kewirausahaan (PKK)",
    "Sejarah Indonesia",
    "Seni Budaya dan Keterampilan (SBK)",
    "Seni Rupa",
    "Tahfidz Al-Qur'an",
    "Teknologi Informasi dan Komunikasi (TIK)"
];
